title: Nat Valentine
logo: /assets/img/logo.png
description: Hi! Feel free to bookmark this to keep an eye on my project updates.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
baseurl: /blog
#permalink: /:year/:month/:day/:title/
