title: Nat Valentine
logo: /assets/img/logo.png
description: This is my personal page. It's where I order my thoughts and talk about my projects. Expect updates.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
permalink: /:title/

# Includes an icon in the footer for each username you enter
footer-links:
  email: natvalentinex@gmail.com
  github: natvalentine
  instagram: nat.valentine
  linkedin: in/natvalentine
  rss: # just type anything here for a working RSS icon
  twitter: natvalentinex
